[ERROR] getFbomBySoFulfillmentid failed: 'NoneType' object has no attribute 'get'
[ERROR] formatting row 0: 0
Traceback (most recent call last):
  File "C:\Users\Thowfiq_S\Project\fdhdataservice\OrderLookUpFunction\test.py", line 166, in OutputFormat
    salesorder = get_salesorders[0]
                 ~~~~~~~~~~~~~~~^^^
KeyError: 0
[ERROR] formatting row 1: 0
Traceback (most recent call last):
  File "C:\Users\Thowfiq_S\Project\fdhdataservice\OrderLookUpFunction\test.py", line 166, in OutputFormat
    salesorder = get_salesorders[0]
                 ~~~~~~~~~~~~~~~^^^
